/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncCenterRouteImport } from './routes/sync-center'
import { Route as SuppressionListRouteImport } from './routes/suppression-list'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MappingTemplatesRouteImport } from './routes/mapping-templates'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as ExportCenterRouteImport } from './routes/export-center'
import { Route as EmailSettingsRouteImport } from './routes/email-settings'
import { Route as EmailAccountsRouteImport } from './routes/email-accounts'
import { Route as DataCleanupRouteImport } from './routes/data-cleanup'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelineIndexRouteImport } from './routes/pipeline.index'
import { Route as ImportsIndexRouteImport } from './routes/imports.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as UTokenRouteImport } from './routes/u.$token'
import { Route as PipelineTasksRouteImport } from './routes/pipeline.tasks'
import { Route as IntegrationsIdRouteImport } from './routes/integrations.$id'
import { Route as ImportsNewRouteImport } from './routes/imports.new'
import { Route as ImportsIdRouteImport } from './routes/imports.$id'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as ApiPublicHooksProcessSyncQueueRouteImport } from './routes/api/public/hooks/process-sync-queue'
import { Route as ApiPublicHooksProcessEmailQueueRouteImport } from './routes/api/public/hooks/process-email-queue'

const SyncCenterRoute = SyncCenterRouteImport.update({
  id: '/sync-center',
  path: '/sync-center',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppressionListRoute = SuppressionListRouteImport.update({
  id: '/suppression-list',
  path: '/suppression-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingTemplatesRoute = MappingTemplatesRouteImport.update({
  id: '/mapping-templates',
  path: '/mapping-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportCenterRoute = ExportCenterRouteImport.update({
  id: '/export-center',
  path: '/export-center',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailSettingsRoute = EmailSettingsRouteImport.update({
  id: '/email-settings',
  path: '/email-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAccountsRoute = EmailAccountsRouteImport.update({
  id: '/email-accounts',
  path: '/email-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCleanupRoute = DataCleanupRouteImport.update({
  id: '/data-cleanup',
  path: '/data-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelineRoute,
} as any)
const ImportsIndexRoute = ImportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImportsRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const UTokenRoute = UTokenRouteImport.update({
  id: '/u/$token',
  path: '/u/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineTasksRoute = PipelineTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => PipelineRoute,
} as any)
const IntegrationsIdRoute = IntegrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IntegrationsRoute,
} as any)
const ImportsNewRoute = ImportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ImportsRoute,
} as any)
const ImportsIdRoute = ImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ImportsRoute,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampaignsRoute,
} as any)
const ApiPublicHooksProcessSyncQueueRoute =
  ApiPublicHooksProcessSyncQueueRouteImport.update({
    id: '/api/public/hooks/process-sync-queue',
    path: '/api/public/hooks/process-sync-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessEmailQueueRoute =
  ApiPublicHooksProcessEmailQueueRouteImport.update({
    id: '/api/public/hooks/process-email-queue',
    path: '/api/public/hooks/process-email-queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/businesses': typeof BusinessesRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/data-cleanup': typeof DataCleanupRoute
  '/email-accounts': typeof EmailAccountsRoute
  '/email-settings': typeof EmailSettingsRoute
  '/export-center': typeof ExportCenterRoute
  '/imports': typeof ImportsRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/mapping-templates': typeof MappingTemplatesRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/settings': typeof SettingsRoute
  '/suppression-list': typeof SuppressionListRoute
  '/sync-center': typeof SyncCenterRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/imports/$id': typeof ImportsIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/pipeline/tasks': typeof PipelineTasksRoute
  '/u/$token': typeof UTokenRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/imports/': typeof ImportsIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/api/public/hooks/process-sync-queue': typeof ApiPublicHooksProcessSyncQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/businesses': typeof BusinessesRoute
  '/categories': typeof CategoriesRoute
  '/data-cleanup': typeof DataCleanupRoute
  '/email-accounts': typeof EmailAccountsRoute
  '/email-settings': typeof EmailSettingsRoute
  '/export-center': typeof ExportCenterRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/mapping-templates': typeof MappingTemplatesRoute
  '/settings': typeof SettingsRoute
  '/suppression-list': typeof SuppressionListRoute
  '/sync-center': typeof SyncCenterRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/imports/$id': typeof ImportsIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/pipeline/tasks': typeof PipelineTasksRoute
  '/u/$token': typeof UTokenRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/imports': typeof ImportsIndexRoute
  '/pipeline': typeof PipelineIndexRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/api/public/hooks/process-sync-queue': typeof ApiPublicHooksProcessSyncQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/businesses': typeof BusinessesRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/data-cleanup': typeof DataCleanupRoute
  '/email-accounts': typeof EmailAccountsRoute
  '/email-settings': typeof EmailSettingsRoute
  '/export-center': typeof ExportCenterRoute
  '/imports': typeof ImportsRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/mapping-templates': typeof MappingTemplatesRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/settings': typeof SettingsRoute
  '/suppression-list': typeof SuppressionListRoute
  '/sync-center': typeof SyncCenterRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/imports/$id': typeof ImportsIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/pipeline/tasks': typeof PipelineTasksRoute
  '/u/$token': typeof UTokenRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/imports/': typeof ImportsIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
  '/api/public/hooks/process-sync-queue': typeof ApiPublicHooksProcessSyncQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/businesses'
    | '/campaigns'
    | '/categories'
    | '/data-cleanup'
    | '/email-accounts'
    | '/email-settings'
    | '/export-center'
    | '/imports'
    | '/integrations'
    | '/mapping-templates'
    | '/pipeline'
    | '/settings'
    | '/suppression-list'
    | '/sync-center'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/imports/$id'
    | '/imports/new'
    | '/integrations/$id'
    | '/pipeline/tasks'
    | '/u/$token'
    | '/campaigns/'
    | '/imports/'
    | '/pipeline/'
    | '/api/public/hooks/process-email-queue'
    | '/api/public/hooks/process-sync-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/businesses'
    | '/categories'
    | '/data-cleanup'
    | '/email-accounts'
    | '/email-settings'
    | '/export-center'
    | '/integrations'
    | '/mapping-templates'
    | '/settings'
    | '/suppression-list'
    | '/sync-center'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/imports/$id'
    | '/imports/new'
    | '/integrations/$id'
    | '/pipeline/tasks'
    | '/u/$token'
    | '/campaigns'
    | '/imports'
    | '/pipeline'
    | '/api/public/hooks/process-email-queue'
    | '/api/public/hooks/process-sync-queue'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/businesses'
    | '/campaigns'
    | '/categories'
    | '/data-cleanup'
    | '/email-accounts'
    | '/email-settings'
    | '/export-center'
    | '/imports'
    | '/integrations'
    | '/mapping-templates'
    | '/pipeline'
    | '/settings'
    | '/suppression-list'
    | '/sync-center'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/imports/$id'
    | '/imports/new'
    | '/integrations/$id'
    | '/pipeline/tasks'
    | '/u/$token'
    | '/campaigns/'
    | '/imports/'
    | '/pipeline/'
    | '/api/public/hooks/process-email-queue'
    | '/api/public/hooks/process-sync-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BusinessesRoute: typeof BusinessesRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  DataCleanupRoute: typeof DataCleanupRoute
  EmailAccountsRoute: typeof EmailAccountsRoute
  EmailSettingsRoute: typeof EmailSettingsRoute
  ExportCenterRoute: typeof ExportCenterRoute
  ImportsRoute: typeof ImportsRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  MappingTemplatesRoute: typeof MappingTemplatesRoute
  PipelineRoute: typeof PipelineRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SuppressionListRoute: typeof SuppressionListRoute
  SyncCenterRoute: typeof SyncCenterRoute
  UTokenRoute: typeof UTokenRoute
  ApiPublicHooksProcessEmailQueueRoute: typeof ApiPublicHooksProcessEmailQueueRoute
  ApiPublicHooksProcessSyncQueueRoute: typeof ApiPublicHooksProcessSyncQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync-center': {
      id: '/sync-center'
      path: '/sync-center'
      fullPath: '/sync-center'
      preLoaderRoute: typeof SyncCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppression-list': {
      id: '/suppression-list'
      path: '/suppression-list'
      fullPath: '/suppression-list'
      preLoaderRoute: typeof SuppressionListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping-templates': {
      id: '/mapping-templates'
      path: '/mapping-templates'
      fullPath: '/mapping-templates'
      preLoaderRoute: typeof MappingTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-center': {
      id: '/export-center'
      path: '/export-center'
      fullPath: '/export-center'
      preLoaderRoute: typeof ExportCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-settings': {
      id: '/email-settings'
      path: '/email-settings'
      fullPath: '/email-settings'
      preLoaderRoute: typeof EmailSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-accounts': {
      id: '/email-accounts'
      path: '/email-accounts'
      fullPath: '/email-accounts'
      preLoaderRoute: typeof EmailAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-cleanup': {
      id: '/data-cleanup'
      path: '/data-cleanup'
      fullPath: '/data-cleanup'
      preLoaderRoute: typeof DataCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/imports/': {
      id: '/imports/'
      path: '/'
      fullPath: '/imports/'
      preLoaderRoute: typeof ImportsIndexRouteImport
      parentRoute: typeof ImportsRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/u/$token': {
      id: '/u/$token'
      path: '/u/$token'
      fullPath: '/u/$token'
      preLoaderRoute: typeof UTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/tasks': {
      id: '/pipeline/tasks'
      path: '/tasks'
      fullPath: '/pipeline/tasks'
      preLoaderRoute: typeof PipelineTasksRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/integrations/$id': {
      id: '/integrations/$id'
      path: '/$id'
      fullPath: '/integrations/$id'
      preLoaderRoute: typeof IntegrationsIdRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/imports/new': {
      id: '/imports/new'
      path: '/new'
      fullPath: '/imports/new'
      preLoaderRoute: typeof ImportsNewRouteImport
      parentRoute: typeof ImportsRoute
    }
    '/imports/$id': {
      id: '/imports/$id'
      path: '/$id'
      fullPath: '/imports/$id'
      preLoaderRoute: typeof ImportsIdRouteImport
      parentRoute: typeof ImportsRoute
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/api/public/hooks/process-sync-queue': {
      id: '/api/public/hooks/process-sync-queue'
      path: '/api/public/hooks/process-sync-queue'
      fullPath: '/api/public/hooks/process-sync-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessSyncQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-email-queue': {
      id: '/api/public/hooks/process-email-queue'
      path: '/api/public/hooks/process-email-queue'
      fullPath: '/api/public/hooks/process-email-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessEmailQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface ImportsRouteChildren {
  ImportsIdRoute: typeof ImportsIdRoute
  ImportsNewRoute: typeof ImportsNewRoute
  ImportsIndexRoute: typeof ImportsIndexRoute
}

const ImportsRouteChildren: ImportsRouteChildren = {
  ImportsIdRoute: ImportsIdRoute,
  ImportsNewRoute: ImportsNewRoute,
  ImportsIndexRoute: ImportsIndexRoute,
}

const ImportsRouteWithChildren =
  ImportsRoute._addFileChildren(ImportsRouteChildren)

interface IntegrationsRouteChildren {
  IntegrationsIdRoute: typeof IntegrationsIdRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsIdRoute: IntegrationsIdRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface PipelineRouteChildren {
  PipelineTasksRoute: typeof PipelineTasksRoute
  PipelineIndexRoute: typeof PipelineIndexRoute
}

const PipelineRouteChildren: PipelineRouteChildren = {
  PipelineTasksRoute: PipelineTasksRoute,
  PipelineIndexRoute: PipelineIndexRoute,
}

const PipelineRouteWithChildren = PipelineRoute._addFileChildren(
  PipelineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BusinessesRoute: BusinessesRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  DataCleanupRoute: DataCleanupRoute,
  EmailAccountsRoute: EmailAccountsRoute,
  EmailSettingsRoute: EmailSettingsRoute,
  ExportCenterRoute: ExportCenterRoute,
  ImportsRoute: ImportsRouteWithChildren,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  MappingTemplatesRoute: MappingTemplatesRoute,
  PipelineRoute: PipelineRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SuppressionListRoute: SuppressionListRoute,
  SyncCenterRoute: SyncCenterRoute,
  UTokenRoute: UTokenRoute,
  ApiPublicHooksProcessEmailQueueRoute: ApiPublicHooksProcessEmailQueueRoute,
  ApiPublicHooksProcessSyncQueueRoute: ApiPublicHooksProcessSyncQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
